### ISSUE TITLE
Main text window doesn't open

### ISSUE THREAD

**Issue by CheckeredFlag** [tonny-kohar/alkitab-suite#4]
After upgrading to v5.0 (mac), the main text window no longer opens.  Clicking "New Tab" has no effect.  Everything else appears to be working properly (e.g. bookshelf, navigator, devotions), but trying to open anything has no effect.

I don't really know Java, but I noticed that there the java.lang.ClassNotFoundException seems significant.

Here's my log file.  I hope it helps you figure out what's wrong.
```
-------------------------------------------------------------------------------
>Log Session: Saturday, October 10, 2020 at 11:26:17 AM Eastern Daylight Time
>System Info: 
  Product Version         = Alkitab Bible Study 5.0 (Build 202009140000)
  Operating System        = Mac OS X version 10.15.7 running on x86_64
  Java; VM; Vendor        = 11.0.7; OpenJDK 64-Bit Server VM 11.0.7+10; AdoptOpenJDK
  Runtime                 = OpenJDK Runtime Environment 11.0.7+10
  Java Home               = /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
  System Locale; Encoding = en_US (alkitab); UTF-8
  Home Directory          = /Users/mmoreno
  Current Directory       = /
  User Directory          = /Users/mmoreno/Library/Application Support/alkitab/5.0
  Cache Directory         = /Users/mmoreno/Library/Application Support/alkitab/5.0/var/cache
  Installation            = /Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/alkitab
                            /Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform
  Boot & Ext. Classpath   = 
  Application Classpath   = /Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/lib/boot.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/lib/org-openide-modules.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/lib/org-openide-util-lookup.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/lib/org-openide-util-ui.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/lib/org-openide-util.jar
  Startup Classpath       = /Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/org-netbeans-libs-asm.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/org-openide-filesystems.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/asm-7.2.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/asm-commons-7.2.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/asm-tree-7.2.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/core.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform/core/core-base.jar:/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/alkitab/core/locale/core_alkitab.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.BookDriver.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /BookDriver.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.BookDriver.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.UserMsg.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/book/UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.UserMsg_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/book/UserMsg_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.UserMsg_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /iso639.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /iso639_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /iso639_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.util.iso639_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.index.IndexManager.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /IndexManager.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.index.IndexManager.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.BibleNames.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.BibleNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.BibleNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/versification/BibleNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.BibleNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.OSISNames.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.OSISNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/versification/OSISNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.OSISNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.OSISNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/versification/OSISNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.OSISNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.SectionNames.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.SectionNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/versification/SectionNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.SectionNames_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.SectionNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/versification/SectionNames_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.versification.SectionNames_en_US.properties
INFO [org.crosswire.jsword.book.sword.ConfigEntryTable]: Ignoring unexpected entry in esv2011 of Versification
INFO [org.crosswire.jsword.book.sword.ConfigEntryTable]: Ignoring unexpected entry in sblgntapp of Versification
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.readings.txt
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /readings.txt
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.readings.txt
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /ot1nt2.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /ot1nt2_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /ot1nt2_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.ot1nt2_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.UserMsg.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/book/readings/UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.UserMsg_en.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.UserMsg_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org/crosswire/jsword/book/readings/UserMsg_en_US.properties
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.readings.UserMsg_en_US.properties
INFO [org.crosswire.jsword.book.sword.ConfigEntryTable]: Ignoring unexpected entry in esv2011 of Versification
INFO [org.crosswire.jsword.book.sword.ConfigEntryTable]: Ignoring unexpected entry in sblgntapp of Versification
Sword Path Configuration
  AugmentPath:
  DownloadDir:
  SwordDownloadDir:
	/usr/local/Cellar/sword/1.8.1/share/sword
  SwordPath:
	/usr/local/Cellar/sword/1.8.1/share/sword
	/Users/mmoreno/Library/Application Support/Sword
  Book Count: 17
  JSword Path: 
	/Users/mmoreno/Library/Application Support/JSword
-------------------------------------------------------------------------------
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.41.1 12.0-u1-efd543aaefdb0a9f8f0073896cb12c82fe4ef9c8]
	org.openide.util [9.15.1 12.0-u1-efd543aaefdb0a9f8f0073896cb12c82fe4ef9c8]
	org.openide.util.ui [9.16.1 12.0-u1-efd543aaefdb0a9f8f0073896cb12c82fe4ef9c8]
	org.openide.modules [7.56 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.annotations.common/1 [1.35 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.filesystems [9.18 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.awt [7.76 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.progress/1 [1.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.progress.nb [1.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.dialogs [7.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.nodes [7.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.windows [6.85 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.mimelookup/1 [1.48 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.text [6.75 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.scripting [1.5 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.tabcontrol [1.64 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.outline [1.42 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.explorer [6.70 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.actions [6.47 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.queries/1 [1.51 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.templates [1.16 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.filesystems.nb [9.18 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.loaders [7.76 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.intent [1.10 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.io [1.11 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.io [1.57 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.plaf [1.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.spi.quicksearch [1.35 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.asm [5.11 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.bootstrap/1 [2.86 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.startup.base [1.70.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.startup/1 [1.70.0.1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.settings/1 [1.57 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.sampler [1.22 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.progress.ui [1.41 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.keyring [1.32 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core/2 [3.59 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.options.api/1 [1.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.options.keymap [1.45 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs/2 [2.63.0.2 2 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.ui [2.11.0.2 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.nio2 [1.23 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.jna/2 [2.3 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.macosx [1.21 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.keyring.fallback [1.16 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.keyring.impl [1.32 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.javahelp/1 [2.49 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.40 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.autoupdate.services [1.63 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.autoupdate.ui [1.54 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.windows/2 [2.93 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.applemenu/1 [1.45 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.jna.platform/2 [2.3 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.ui/1 [1.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.output2/1 [1.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.network [1.20 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.nativeaccess/1 [1.39 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.multitabs/1 [1.20.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.io.ui/1 [1.38 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	kiyut.alkitab.modules.userguide [5.0 200914]
	kiyut.alkitab.modules.swingfx [1.0.0.20080506 200914]
	kiyut.alkitab.modules.jsword [1.6.0.20091003 200914]
	kiyut.alkitab.modules.javafx [11.0.2 200914]
	kiyut.alkitab [5.0 200914]
	kiyut.alkitab.modules.branding [5.0 200914]
	kiyut.alkitab.modules.localization [5.0 200914]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Mac
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading failed! Trying fallback resolver.
INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded. Fallback provider was successful.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO [kiyut.alkitab.modules.branding.BrandingModuleInstall$1]
java.lang.ClassNotFoundException: com.sun.glass.ui.mac.MacPlatformFactory starting from ModuleCL@6fb84b8d[kiyut.alkitab.modules.javafx] with possible defining loaders null and declared parents ]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.mac.MacPlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
	... 11 more
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.filter.Filter.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /Filter.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.jsword.book.filter.Filter.plugin
WARNING [org.netbeans.ProxyClassLoader]: Should not use initial / in calls to ClassLoader.getResource(s): /org.crosswire.common.swing.BookFonts.properties
Diagnostic information
Input arguments:
	-Djdk.home=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
	-Dnetbeans.dirs=/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/alkitab:
	-Dnetbeans.home=/Applications/Alkitab Bible Study.app/Contents/Resources/alkitab/platform
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/Users/mmoreno/Library/Application Support/alkitab/5.0/var/log/heapdump.hprof
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 256.0MB maximum 4096.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=5 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=7448 total loaded=7448 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 17,179,869,184
INFO [null]: Total physical memory 17,179,869,184
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@38913005[MultiFileObject@6b18a26[Shortcuts/M-BACK_SPACE.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@5c38faf3[MultiFileObject@285c46cc[Shortcuts/M-R.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@3e6211e5[MultiFileObject@1bab7c6c[Shortcuts/O-G.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@38913005[MultiFileObject@6b18a26[Shortcuts/M-BACK_SPACE.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@5c38faf3[MultiFileObject@285c46cc[Shortcuts/M-R.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@3e6211e5[MultiFileObject@1bab7c6c[Shortcuts/O-G.shadow]]
```

**Comment by tonny-kohar** [comment]
It seems it is a bug related to JavaFX (just introduced in Alkitab 5.0), I will look at it

**Comment by tonny-kohar** [comment]
Would you mind to check the new build (v5.0.1-beta) that I think fix the issue, it is available at
[https://www.kiyut.com/products/alkitab/alkitab-beta-mac.zip](https://www.kiyut.com/products/alkitab/alkitab-beta-mac.zip)

It will be very appreciated if you could try the above version and provide me with feedback whether the the bug is indeed fixed or not on you side. 
Note: Or any Mac user, since I don't have Mac OS for testing, I rely on the Mac user to provide feedback

**Comment by CheckeredFlag** [comment]
That fixed it - thanks!

BTW, I'm happy to beta test releases for Mac in the future.  Just let me know.

**Comment by tonny-kohar** [comment]
Thanks for the feedback, it is very appreciated. And thanks for the offer for beta testing Alkitab in the future, I will contact you in the future for beta test mac version.
